### ISSUE TITLE
全是 any

### ISSUE THREAD

**Issue by DiamondYuan** [Tommy-White/dva-utils#1]
真的建议在 ts 中不要使用任何 any。否则就失去了 ts 的意义。

**Comment by Tommy-White** [comment]
@DiamondYuan  
Typescript 目前主要用于类型安全性检测，会精确类型定义但其中还是存在一些使用`any`的场景，例如：对变量类型的检测(`any => predictions`)，以及一些开放性接口等。
> In these cases, we want to **opt-out of type checking** and let the values pass through compile-time checks. To do so, we label these with the `any` type:

**Comment by lihroff** [comment]
commit ea0c1604d5a3b4c7aba8556413c14d73abe1cc01
